### ISSUE TITLE
handle not given keys of find_existing_by-definitions as blank

### ISSUE THREAD

**Issue by alexanderadam** [vigetlabs/sprig#42]
currently if I chose to set something like

``` yaml
options:
  find_existing_by: ['foo', 'bar', 'baz']
```

I have to provide all three keys even if I decide that one of the keys can be blank.

so instead of

``` yaml
records:
  - sprig_id: 1
    foo: bla
    bar: bla
    baz:
```

I would love to keep it

``` yaml
records:
  - sprig_id: 1
    foo: bla
    bar: bla
```

I hope I described it somehow clear!? :wink:
