### ISSUE TITLE
Dependency sorting not working with string keys

### ISSUE THREAD

**Issue by yaychris** [vigetlabs/sprig#91]
Given the following two seed files:

```yaml
# photos.yml
records:
- sprig_id: 1
  name: 'Photo 1'
  site_id: "<%= sprig_record(Site, 'cooldev').id %>"

# sites.yml
records:
- sprig_id: 'cooldev'
  name: Cool Dev
  key: cooldev
  domain: cool.dev
```

if I run the following command:

```ruby
sprig [
  Photo,
  Site
]
```

seeds do not work:

```
D, [2016-11-21T14:17:32.050772 #41433] DEBUG -- : Planting Photo with sprig_id 1
E, [2016-11-21T14:17:32.353571 #41433] ERROR -- : Record for class Site and sprig_id cooldev could not be found. (Substituted with NullRecord)
E, [2016-11-21T14:17:32.428034 #41433] ERROR -- : There was an error saving Photo with sprig_id 1.
E, [2016-11-21T14:17:32.428135 #41433] ERROR -- : #<Sprig::Seed::Record:0x007fe55888d958>
E, [2016-11-21T14:17:32.428259 #41433] ERROR -- : {:site=>["can't be blank"]}
D, [2016-11-21T14:17:32.428316 #41433] DEBUG -- : Planting Site with sprig_id cooldev
I, [2016-11-21T14:17:32.533419 #41433]  INFO -- : Saved
D, [2016-11-21T14:17:32.533508 #41433] DEBUG -- : Seeding complete.
I, [2016-11-21T14:17:32.533553 #41433]  INFO -- : 1 seed successfully planted.
E, [2016-11-21T14:17:32.533590 #41433] ERROR -- : 1 seed couldn't be planted:
E, [2016-11-21T14:17:32.533624 #41433] ERROR -- : #<Sprig::Seed::Record:0x007fe55888d958>
E, [2016-11-21T14:17:32.533669 #41433] ERROR -- : {:site=>["can't be blank"]}
```

If I switch the order to this:

```ruby
sprig [
  Site,
  Photo
]
```

then the seeds work as expected. Also, if I change the site `sprig_id` to an integer, it works in either order.

My best guess is that the dependency sorter is not correctly sorting records with string keys.
