### ISSUE TITLE
Sprig won't evaluate sprig_content erb for hstore column.

### ISSUE THREAD

**Issue by ritec** [vigetlabs/sprig#95]
Hello there, I am running into an issue where `sprig_record` is not being evaluated when nested  2 levels deep. I am using Postgres with hstore and storing a hash called `data` When I look into my DB after seeding it with the example file below the data hash for sprig_id 1 will show as `{data: {pre_test_content_id: "<%= sprig_record(Thing, 40).id %>"}` without evaluating and finding the id for sprig_record 40.  I tested evaluating` "<%= sprig_record(Thing, 40).id %>"` by putting said line in the description field and it did indeed evaluate properly by storing the correct record id, but this is not the case when 2 levels deep as in the example below.

```
  - sprig_id: 40
    name: "Some Test Name"
    description: "lala"
    data:
      slug: "some_slug" 
  - sprig_id: 1
    name: "Another Name"
    description: "desc"
    data:
      pre_test_content_id: "<%= sprig_record(Thing, 40).id %>"
```

Any help or possible work arounds would be greatly appreciated. 
Thanks!

**Comment by ritec** [comment]
Never mind, I was able to make it work by having the data key be at the root level, after the hstore attribute like so:

```
  - sprig_id: 40
    name: "Some Test Name"
    description: "lala"
    data:
      slug: "some_slug" 
  - sprig_id: 1
    name: "Another Name"
    description: "desc"
    data:
    pre_test_content_id: "<%= sprig_record(Thing, 40).id %>"
```
